export const Env = [
  "PORT",
  "SUPABASE_URL",
  "SERVICE_ROLE_KEY",
  "ANON_KEY",
  "MONGO_URI",
  "BINANCE_API_KEY",
  "BINANCE_API_SECRET",
  "BINANCE_TESTNET_API_KEY",
  "BINANCE_TESTNET_API_SECRET",
  "DISCORD_APPLICATION_ID",
  "DISCORD_PUBLIC_KEY",
  "DISCORD_BOT_TOKEN",
  "DISCORD_LOG_CHANNEL_ID",
  "DISCORD_BUOB_CHANNEL_ID",
  "DISCORD_BUY_SIGNAL_CHANNEL_ID",
  "DISCORD_WS_CLOSE_CHANNEL_ID",
  "DISCORD_WS_DEBUG_CHANNEL_ID",
  "DISCORD_CONDITION_15M_1_CHANNEL_ID",
  "DISCORD_CONDITION_15M_2_CHANNEL_ID",
  "DISCORD_CONDITION_15M_3_CHANNEL_ID",
  "DISCORD_CONDITION_15M_4_CHANNEL_ID",
  "DISCORD_CONDITION_15M_5_CHANNEL_ID",
  "DISCORD_CONDITION_30M_1_CHANNEL_ID",
  "DISCORD_CONDITION_30M_2_CHANNEL_ID",
  "DISCORD_CONDITION_30M_3_CHANNEL_ID",
  "DISCORD_CONDITION_30M_4_CHANNEL_ID",
  "DISCORD_CONDITION_30M_5_CHANNEL_ID",
  "DISCORD_CONDITION_1H_1_CHANNEL_ID",
  "DISCORD_CONDITION_1H_2_CHANNEL_ID",
  "DISCORD_CONDITION_1H_3_CHANNEL_ID",
  "DISCORD_CONDITION_1H_4_CHANNEL_ID",
  "DISCORD_CONDITION_1H_5_CHANNEL_ID",
  "MAX_OB_WORKER",
] as const;
export type Env = (typeof Env)[number];

declare global {
  namespace NodeJS {
    interface ProcessEnv {
      [key: Env]: string;
    }
  }
}
